spring:
   application:
      name: eureka-server-clustered
server:
   port: 9002
eureka:
   instance:
      hostname: eureka-2
      metadataMap.zone: center
   client:
      preferSameZoneEureka: true
      healthcheck:
         enabled: true
      registerWithEureka: true
      fetchRegistry: false
      region: pt
      serviceUrl:
         defaultZone: http://localhost:9001/eureka/
         center: http://localhost:9002/eureka/ 
         north: http://localhost:9001/eureka/      
      availability-zones:
         pt: center, north
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:18 :#   region: center
# Was at begin of line:19 :#    serviceUrl:
# Was at begin of line:20 :#      defaultZone: http://localhost:9001/eureka/
# Was at begin of line:21 :#      north: http://localhost:9002/eureka/
# Was at begin of line:22 :#   availability-zones:
# Was at begin of line:23 :#     center: defaultZone,north  **/