spring:
  application:
    name: movie
server:
  port: 8090
  
eureka:
  instance:
    metadataMap.zone: center
  client:
    prefer-same-zone-eureka: true
    region: pt
    serviceUrl:
      defaultUrl: http://localhost:9002/eureka/
      center: http://localhost:9002/eureka/
      north: http://localhost:9001/eureka/      
    availability-zones:
      pt: center, north